apiVersion: v1
kind: Secret
metadata:
  name: books-webdav-auth
  namespace: webdav
type: Opaque
stringData:
  user: ENC[AES256_GCM,data:WcJmvr4=,iv:CT58ok54ARmzTYeziDszo2k1jpGBigv0NClSI9R3fH8=,tag:ztDU6wg71VZhEKV5bjvMSg==,type:str]
  password: ENC[AES256_GCM,data:aVoglp1WcR9ST5w8GwW8HEoDYd8=,iv:MPxzoX2BiifqkA/fiLU+E5iv0QgREpRoBkhJJngadqE=,tag:IC2BpA1MHwUnBhDUK48JDA==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUkpYSkN0U1RpRlZkRWpH
        LzhwQSs2ZXFISzk0eDhGVzcyNVltcU1GRkEwCm43YXpqTVczRURwb3RHdDdrc2E2
        bTRZYmhobFhtaGxEODBvQTdHRnFER28KLS0tIHh6Qk5TN05QNXh4Y295Y0tjejJI
        d0hLOE9SL1N2YjF0MnFjbERxSXhlODAKB933fBn6Xl5a6KfAjMuqwjHGT8Ny+hPv
        PyDPIBr+cDqBQPwP8MhDMNRZ6x8b/tHHZgNG9YqDbSd9KBdRC4CQmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T17:30:31Z"
  mac: ENC[AES256_GCM,data:y7pIq3ZA/vBI4oRVSPMjFhDFrzL4eGR9NnufAkBXgtHhbsw37x/10hYie3QrdfrvaSbCoYZUDftUxTTmKLx1kkBHTaAVGurKcR5LGUArhLqRkPhrKwyCE6VCzCc7Pt9rnaNScT+3XXAzQNIXMHbTTQKoO/OuCvlLU+bbOOA71aA=,iv:RtlPOoSNFN72A8vwMYHVP/SqakF63c1GWhXFNMzVaF8=,tag:GRb6xVKrkkJmpp3R//bDxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
