apiVersion: v1
kind: Secret
metadata:
  name: books-webdav-auth
  namespace: webdav
type: Opaque
data:
  user: ENC[AES256_GCM,data:3/qCSDY=,iv:p979JCVApUxvMEBesQEJ/uOC2byY6085h8GQTpeIIY0=,tag:qd+FVgIgMZ5Z9TZrj9YtNg==,type:str]
  password: ENC[AES256_GCM,data:dF0hyc39GJRYg4RJYgDwYmV61bA=,iv:/nf/RhXsIAieM8ZyMVP1fE1TvOL3s66g0p8zjQ99xig=,tag:UR/wiMsqGgSOW3ToB6uvCA==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXo4N2I4RnFLeFRYcnQv
        LzZEQmp3M1U1MCtlSDEvN3B1THE1RWZ1eGdvCjhuZ2R5UVVLbTVMbjV3eUErU2dM
        RjQ4cVZiWEllUm56UFgyQmtCNFpWRFkKLS0tIG1taWR5dkpkenJmWmxpelF6ZThM
        M0RqU3k3ckQ0LzJ1ZkZLK2NyRXJ2ZzQKVs1gsmXB48wnKfPNukJBDkYU/ANNDspy
        IlSO7yowpkVM1OCqiHBzqTtd3UD3jVmZAZjXRHqcRusOfelkwFHgvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T17:28:52Z"
  mac: ENC[AES256_GCM,data:Aj7AKEEVTvzqXH73icmkgIZ7j3M9/9MbretX2Alj8VQK7txzTx8d2bMFmJfNnqS03mQ7LknoSqDfotSYtsx/JAZtTLZCSRWcm0UjCmGDeyUUUstLjGoWzNYFPDgnZbZ3QfabOQ7YfVzZgT4coihE48HjQv+5Vx9o4FVWtM8wXwQ=,iv:XIi+FJN1p5j16Eih2iXDiHpJcmKRnxyAaCGBt3OICQY=,tag:uHBd6yRUvPmkzGcIN7m+SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
