apiVersion: v1
kind: Secret
metadata:
  name: books-webdav-auth
  namespace: webdav
type: Opaque
data:
  user: ENC[AES256_GCM,data:TwPnRqU=,iv:RTb4NIRLuZ8EYBJiGZ+rhGHJxKM/N6WfgXeAceD6vs4=,tag:5xNInjRh9CPm3C2R+EkAng==,type:str]
  password: ENC[AES256_GCM,data:MC43oq8bBXBWax30fxYoXjhMb88=,iv:8XuYv/yseL3++63lhT7RA9PBp5lmfmyvaUxQXQA/gPs=,tag:KXwIVPyll1tFHCh2YeEVzA==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bVNIQ2dzSFlBRWRPOTYw
        a0ZadUtiZXA5dHErNmJSMWV4VmNvME51Q1VFCmxrLzhoVDVhdlFTNjlWcjFtYlQ4
        RXI1WTgwZU1GczFlNEhSSFJYWnJSRU0KLS0tIGJtcGhQTHVQcjZQYktsOFh2RzVW
        SVFRZ3RPbnFYT0VRQ3kxTFBZU0dWSU0KZL1eeRg6KrC2YtQO9CDtdYX3ymSqra/4
        Av0N8kQOfsA2DAkGjcr9T9rH4AtcdAYyBdXx2k51vmraDjQLsCSL5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T17:24:33Z"
  mac: ENC[AES256_GCM,data:hggxRG3/v3rb1kRwDlOwHdZF+Sh0ohDiIXfd7VF0X69K9nSY7hu01LgdwmY/tlnRb4kuDu3216jc2+gOPy/FfUDmGxA3mhmKlMvewR8yb7Mtab3RfoiF0nHgbxaLsU7JgnUv1HVy/mWfN/L4OFdbKK9as7CwtYglLy4ShXXacGI=,iv:onpCb4t/CZ6yknAUPi6OIXASZC0TbXSPwKGrv8/MONI=,tag:BtAG9pxnFl1Q1Xy0h2KMyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
