apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  namespace: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: books-pvc
      containers:
        - name: rclone
          image: rclone/rclone:latest
          args:
            - serve
            - webdav
            - /data
            - --addr
            - :80
            - --user
            - "test"
            - --pass
            - "test"
          volumeMounts:
            - name: books
              mountPath: /data
