apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
  namespace: webdav
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
  volumeName: books-pv
