apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: arrstack
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "radarr"
    tailscale.com/proxy-class: "triss-pinned"
spec:
  selector:
    app: radarr
  ports:
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 7878
