apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: default
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - immich
  rules:
    - http:
        paths:
          - backend:
              service:
                name: immich
                port:
                  number: 80
