apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: default
spec:
  ingressClassName: tailscale
  targetNamespace: default
  defaultBackend:
    service:
      name: immich
      port:
        number: 80
