apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-api-ingress
  namespace: default
  annotations:
    tailscale.com/hostname: desktop-kube-api
    tailscale.com/backend-protocol: "https"
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes
            port:
              number: 443
