apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: default
  labels:
    app: immich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
        - name: immich-redis
          image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: default
spec:
  selector:
    app: immich-redis
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
