apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: default
spec:
  interval: 1m
  url: https://immich-app.github.io/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
      version: 0.10.3
  interval: 1m
  values:
    immich:
      persistence:
        library:
          enabled: true
          existingClaim: immich-media-pvc
        database:
          enabled: true
          existingClaim: immich-data-pvc
          subPath: postgresql
        redis:
          enabled: true
          existingClaim: immich-data-pvc
          subPath: redis
