apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: default
  labels:
    app: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      volumes:
        - name: immich-media-storage
          persistentVolumeClaim:
            claimName: immich-media-pv
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:latest
          ports:
            - containerPort: 2283
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              value: immich
            - name: DB_DATABASE_NAME
              value: immich

            - name: REDIS_HOSTNAME
              value: immich-redis
          volumeMounts:
            - name: immich-media-storage
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: default
spec:
  selector:
    app: immich
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2283
