apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql
  namespace: default
spec:
  selector:
    app: immich-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
