apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-media-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-immich-media
  nfs:
    path: /mnt/data/photos
    server: storage.host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media-pvc
  namespace: default
spec:
  storageClassName: nfs-immich-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
