apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-pvc
  namespace: default
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-data-pvc
  namespace: default
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
