apiVersion: v1
kind: Secret
metadata:
  name: audiomuse-ai-secrets
  namespace: default
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:foIXd7FHloI79oUMvtCSEzpZJQt7eF1Sb5vtB9MVrpT6eLsRY1ImlUUiUCcreP18gd/b+Qz+fWrJEQp79mM=,iv:aQAE2pZ6hHtsNnRA46C6yIsoFi/8n3mKyHOTsq2rd7A=,tag:8jdkiE0t4eReVLrxaarmrg==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcnJYcFAxZ0wySVhmbDln
        OFozS0tTUys1RWx2TWc0QjRNY1gyZXFCM3pBCklTK2Uzd2FXV2VSWFd6RlpML2VJ
        V3BRNFVpdnk1YTZzMXltS0NiSjh4SWcKLS0tIEFLMWlVNFpZenNZa00rTWxtMmxB
        MWZ2eEJHWklnZEQzaFFIUWJneXlCWjgKyGvTZAUYeErNGEBxF+gfRB+eA3slc1cD
        THt09V5E7VBSEnjD8V8XplrpIiP9jCxwToMZMv1U+rZvE1oXMzxv4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T21:45:56Z"
  mac: ENC[AES256_GCM,data:XufpUOTgKpV+40nm+FekBmQKEGmMp6AZhPgXZ68ijFY1eFisD6DDoeSXkNvZRaQ9E30RsSQYrPPNqHDdvYb/bK3bEhIj+iRrZtO1wKrm1eXDpgts6hsZbTjVj1VZXA/xaO+DKbfYRSRLV4bynkJcgE8J9jo90udWoKb48S1xy9M=,iv:gZjuly7byFlshl4pqDzzjTC+O4RJrr+Yy7ulhFMsYp0=,tag:suPrdKdkN/YWbrc5bCm9jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
