apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: arrstack
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "lidarr"
    tailscale.com/proxy-class: "triss-pinned"
spec:
  selector:
    app: lidarr
  ports:
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 8686
