apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "default-replica-count": "1"
    "backup-target": "nfs://100.109.230.83:/persist/apps/longhorn"
    "backup-target-credential-secret": ""
    "backupstore-poll-interval": "600"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-nfs-backup
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"
  task: "backup"
  groups:
    - default
  retain: 7
  concurrency: 1
