apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gutenberg-books-pvc
  namespace: cron
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
  volumeName: gutenberg-books-pv
