apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: arrstack
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: triss
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: webui
              containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: sonarr
            - name: downloads
              mountPath: /downloads
            - name: shows
              mountPath: /tv
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: arrstack-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: arrstack-downloads-pvc
        - name: shows
          persistentVolumeClaim:
            claimName: arrstack-shows-pvc
