apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arrstack
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "sonarr"
spec:
  selector:
    app: sonarr
  ports:
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 8989
