apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: triss-tailscale-operator
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.92.5
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  values:
    operatorConfig:
      hostname: "triss-tailscale-operator"
      resources:
        requests:
          memory: "32Mi"
          cpu: "10m"
        limits:
          memory: "128Mi"
          cpu: "300m"
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: client-id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: client-secret
      targetPath: oauth.clientSecret
