apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: arrstack
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      nodeSelector:
        kubernetes.io/hostname: triss
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "UTC"
          ports:
            - name: http
              containerPort: 8191
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
