apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: navidrome
  namespace: navidrome
spec:
  selector:
    matchLabels:
      app: navidrome
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
