apiVersion: v1
kind: PersistentVolume
metadata:
  name: arrstack-downloads-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 100.109.230.83
    path: /tmp/arrstack/downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arrstack-shows-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 100.109.230.83
    path: /mnt/data/shows
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arrstack-movies-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 100.109.230.83
    path: /mnt/data/movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arrstack-music-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 100.109.230.83
    path: /mnt/data/music
