apiVersion: v1
kind: Secret
metadata:
  name: mullvad-egress-auth
  namespace: tailscale
type: Opaque
stringData:
  authkey: ENC[AES256_GCM,data:HxTALe2lXrXRdAs8pOpIV1Jfe75nsGspV/iCsoe0jpQnxMJuwTA1WNRRe7f3zwfn31R8/WjVDamjbD8oGw==,iv:6QNE7qkNlu8p8QPnIg+V61Wh9QhOlEYiNxNpDc1bz+Q=,tag:6GZrvneN2aIZBUiBCsczeg==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S2hWU2NKb0ZmdXlySHk4
        R2dlVVd3U0lHQlhlUVo2bjlESS9yZU1UL1NzCkNHeWpsM0t3VnFIYkl5VEpTV0JZ
        Vnh0SDducDJPeWN6UjlPeTJXY3lwOTQKLS0tIGNZL3BJNE53a3M0SmEyNmYrcDdB
        cXUvQ2NJZ29yaW5jWmlZaGh1TnRpTzgKfg7l3OO/UpBxSylMGMIjPbfzqg4jYdz7
        tuPO5lvoISTzhBVl9xBXN+KuMuBXzZm8xN0cgntthNzpGSY0pnFEWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T17:32:43Z"
  mac: ENC[AES256_GCM,data:mjl1BNzk86SJ82yBOhOxJUsWx4+XvzckBTbACF36dxwHwtoAFlCRPIMYw0CHSKRLmYkoysOfzASe04AWuL10N4oJc4CUT37fDnBLkh/QVeD4hMDIg6QfF0sy9Jszpyi7RpVDbG54kjMP+5OX0QqiWbqPksjlqq4T+X9AA6WACds=,iv:YUPXGVuTHC9wBdz/aA0b0njGfstZuZTGlmTj+n9AKdM=,tag:t7Eiu6/P+WqliCw2Z35cHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
