apiVersion: v1
kind: Secret
metadata:
  name: mullvad-egress-auth
  namespace: tailscale
type: Opaque
stringData:
  authkey: ENC[AES256_GCM,data:yk61mByJyCUBTShj57w1ZJZXoX5xtOSiRGKg5Q3wws0BJvx/nQlADtLaOrYT1ozgkiRVnRRWwmkcf5zN4Jw=,iv:/FgUlvoIaphS6bfM/OouBjN/f0GHGN+alqA2lP8zp6o=,tag:OD4fJb3haiJkcll0NzgWbQ==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZElIa3AyRytpV29hdFlL
        cFhaUC9uT29wWUdDUi80T29pSjg1WEtTdmhNCjBtMEtoN2E5bUw4RmxRTHp5eG1s
        K0NYcGlNTldPdEMxc1ZpUlpXUGlERjgKLS0tIDFId0RxN2wxeE9qSkZqd2V4Y09M
        dGIxQVV0cEppVnZiWG5QOHJYeFJ3L1kK9dIQ2zWtqvlzXS9rO8wvx7Jv9MKJ5ND6
        iCzI+3EOQdwvfEgXlOF2oUGuQofwmFfmDzdXSVDwS13r3E3o2/gWCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T17:23:46Z"
  mac: ENC[AES256_GCM,data:iqLjDrdNRYJ7wkWscUZbicA9dqQum7tLMph9nC0SZANLrU/d2IJ2AGvu1yzZvUmMjjLVrRjpAl9tRZU4Ivx7Zm75NuZ8bmQIg7GwUvKqk8hpJnBko6SmqdotszBhSxCn1JkHznfywIEIFQiEXRD2d3tIe8mxb6ZTGAqeYgjnGE8=,iv:nnvTXzj+6ZGE/z1WZtCuomBEBDi2718mJN9ZQqTmpRk=,tag:W85epML6QHHfWjSDwJFfZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
