apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: nfs-backup-target
  namespace: longhorn-system
spec:
  backupTargetURL: "nfs://100.109.230.83:/persist/apps/longhorn"
  credentialSecret: ""
  pollInterval: 10m0s
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-nfs-backup
  namespace: longhorn-system
spec:
  cron: "15 * * * *"
  task: "backup"
  groups:
    - default
  retain: 7
  concurrency: 1
