apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
data:
  credentials.json:
    AccountTag: ENC[AES256_GCM,data:VKX6zctRo4y7adUbRGMOgSiS9PEA1Z5CRXzKWxfpqhM=,iv:oHpuo18/BpUn/5RtM9p4QlziyvhT0/VlVF0eUQfq0g0=,tag:CRJv5HCqPBogUon33FT1ow==,type:str]
    TunnelSecret: ENC[AES256_GCM,data:oNLAQnzWjBJqklTt58X5wlzzsp/dbbD7aL48ISCj4qKaMSKiz8pBMP3rYz0=,iv:GzvhS9AXM1h8DI1BhX9G4JvvDCMRHcVMDfXkKM2xDao=,tag:LbBV0BVZqgQdfw7WHCn9sg==,type:str]
    TunnelID: ENC[AES256_GCM,data:4pnhd6YO3jQrPfJOcd1ogUadL2vIGjRhcTRKDy4pfSXhOxHf,iv:G/aO2wlWCOwBcfG9NTACG2f6cAIDtHIddS2Jotu4ffU=,tag:mXDgIU3LV1uceVO7z68HcQ==,type:str]
    Endpoint: ""
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWXhUVFJoRGpWeHozb0pB
        empONEdRSXdVbGgxR09SRUwxUUdaZjd0aFFjCndiTHAyY2tGa1NQZk9PQncyZ09r
        aTdjdEt0S3ZnR3QvRVUzOWhTd3pKY1kKLS0tIG9FQ1NsZm1Tc3BlVWZvdGhHWlhC
        ZE12UlgrRDZGdmNaN1h3VHRTVWZvT0EKVqmdp99Ova+pb7GJyoWzetSG3cfq4omW
        VxNAfj38KpNqCjiILRvf/itiVY5slGc9pblBD54FloYEJLTif1ZMuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:45:15Z"
  mac: ENC[AES256_GCM,data:mzDgbbK4c7JFJGTEUPBDGCU3WjdQcgRocnxCOjGPtbbqEgKq7bri5hn0vIXjOAsHa+BzjEmyywHuNjtwW4WSJPmBJt6afIjKpXdrfWPbycxxTWJOkSUx/oONz6eOTY1nc5S1JtE1g98fmUnVL/Out+vEdcnGc9eYZ/jn2hgxuLI=,iv:FJO1uJNE+X0fLpVTEs59gh+aLKF8Pb9be7kdqvxEZHY=,tag:+dss3CUQgTfYUn8lJXeWNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
