apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
stringData:
  credentials.json:
    AccountTag: ENC[AES256_GCM,data:5aovGXAh36zRePebbF6RpiFDg9ggj2V5UEnB+Uue6gw=,iv:oRfBFxhz4Tgh9zLLH2cEwUElwo4wcTRA+tT+fngkH7k=,tag:AZbuUwjiSqNcbHI2LOaGHQ==,type:str]
    TunnelSecret: ENC[AES256_GCM,data:TgN8gIgv2LstmX7Gk2thtjAwEMFkQ1RfvGUjf8ULkX6IPA1uSOCREgkAdP8=,iv:r8WEcV3d64ZqhkFO1t6bh77MuL+u+W+XTRVCUYm4QJc=,tag:2CGB6AevGI94koAfgEsllA==,type:str]
    TunnelID: ENC[AES256_GCM,data:qdys8ksvtojCD7Bxfh87N86wvKw+cb4nN79ju/awTBboah3g,iv:BWqWKD62ZtmLbq/jkqegD1URyuiOtxq7n3Zg5YZo0UE=,tag:A4/c5RA9f2Jeta4dA4jPIA==,type:str]
    Endpoint: ""
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNjRqRjkyZGdwMHRhbW9V
        T29PRlA5VHh0ald1QU44QU5qb0dmMlBXRWprCkFOQkRTbTV4enF4UXdZVGYyMk81
        SGlKZndhY3VQQm5SMWNJbEVtZktJUlkKLS0tIHVtR1FlUWJ1NHoxdHc5OC9RV0o2
        aTNPTE1QM0YvYTJqMkhrbHl4YVpuWVkKv6EC7omhCydJIoyQ/K1dNs9KZscFPhI1
        F/PPrk57/Zr+DjN0M6fbrWITTkShfJMalK1uwZ1evntwbj4O5hbPXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:47:15Z"
  mac: ENC[AES256_GCM,data:WAAPCn9noex7Kn802fw+JYb9LAmydPVDQi4kt9l6ZVsoXRSreGhshhoCTPU9zMx66YAlnQNkVvUGUUqlS3Qfh4ZRJiSKOgmaM37CBqIzYMIv6jhKm3ptPDhOKS9J6ite9O2vHMupglGKRFnCijew9dYvkUZFjyw9o3xm5c6pCgk=,iv:v/BMgHUU7irsFX7m/lr6JF6HLmHHshFPzCuzo1pxbN0=,tag:kXHxp9psfHRlhDo4lGJf4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
