apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:mHv2NspqZ213qcRf5W06GDbmH0AtYcmTO/ix+3VFSw4asHTcWXOjjGfsnKOqnZ7OzICBRdWH+92omv2nnA7PgmhT5DR9x+yNsKUIIeDVEy8H/xHKMvMF/QksrvPHFXvaNmWAwWTaiZyA6+hDXs9f9BTiOE+Ra1ho2Sgc3ZdDCIc36SwRgwlD2k9xM8sF0qv6W002PhaBMlwBHIhtSkDczNDLAF1UFZgMPeCbrGi+6Og=,iv:YZ8Rl6fs+0mi+yJmBIqpIVQ4mzPNvAiOvGwEH7+rFA8=,tag:JPZQ0RAWq4eVVJfVIGd/Dg==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNXE5NGM2aHhIcm5UV2FP
        dndpWXZ0YmRHUm9qaGlpeTk4bmZFbG9QRUNnClgzbjBGWFAxVENZSENCajV2OFNv
        NkVVYS9xYTYzaERlWDBZWXlPeGtOZTAKLS0tIGdGMkUwQUZJa3dGYXV3R280N1Jo
        Y28rTGQ3cTRCWmlIbXJsWGNZVU1PblkKW5uOh0d9EDZhq8KyybaJWTZb4dVLAt5W
        MPQ0RMvzkPiDwSJEIaBmrIY1skPJ1xRUrxOMQdXdXB+pWeL8VPnhQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:53:51Z"
  mac: ENC[AES256_GCM,data:OB6p/ZE+nbepenT0BxeSX/MDKgFSz0D21KpvkHq+36aTK/c35Q0TZ7cBvF+m44cPdqlv8lRqdSgIPSw727VIyC+z0Qi+ftNYF26970/BeSvemRtnA0wp3iXoVVSfifL9sXoCRkJhQxOaZulayMPkJDCx3SlLos53MleqHlCMTI8=,iv:lLhMi5oMorsK6FHjG8qWrINvNiBhLfTfmWqHAvlzIK8=,tag:djPp861npBGSuXfnRVfv4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
