apiVersion: v1
kind: Service
metadata:
  name: audiomuse-ai
  namespace: navidrome
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "audiomuse-ai"
spec:
  selector:
    app.kubernetes.io/name: audiomuse-ai
    app.kubernetes.io/instance: audiomuse-ai-release
    app.kubernetes.io/component: flask
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
