apiVersion: v1
kind: ConfigMap
metadata:
  name: audiomuse-ai-config
  namespace: navidrome
data:
  values.yaml: |
    resources:
      requests:
        memory: "128Mi"
        cpu: "20m"
      limits:
        memory: "384Mi"
        cpu: "500m"

    postgres:
      persistence:
        enabled: true
      user: "audiomuse"
      password: "audiomuse"
      aiChatDbUser: "ai_user"
      aiChatDbUserPassword: "aipassword"
      resources:
        requests:
          memory: "64Mi"
          cpu: "20m"
        limits:
          memory: "128Mi"
          cpu: "300m"

    navidrome:
      url: "http://navidrome.navidrome.svc.cluster.local"

    config:
      mediaServerType: "navidrome"
      aiModelProvider: "OLLAMA"
      ollamaServerUrl: "http://ollama-service.ollama-system.svc.cluster.local:11434/api/generate"
      ollamaModelName: "llama3.1:8b"
      aiChatDbUserName: "ai_user"
