apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  namespace: owncloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
  volumeName: files-pv
