apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:/9bidjtkvsZsprvqlPkAUfqqD+2EkY5PY/iMrYKNj1CY2xkJ3rCSFB8elDiFNhL6b0XtWJhdgufnP8YNof1UAGpCTdeW4OsgGfVkZIn+iTjxqkXbUgNu2dZpXjPLtCXswlYngbb+YmGY8E4mDCIiodm6k/M2NtzWun92KfRFXenNDmX60E6ym3iVweyrIkEiasVWGZxWqFJryjf5dCfWcy9H2EUwbPGL3X8m1c3ZuWE=,iv:tekjhosLKvd5ElTDa482YBbVzIEngVjblu1cnTGG3Ww=,tag:HOvsfxdqw6BQbue6FPKYlw==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlBGYmlyU1VqVzdmMHUr
        WHYrYzE2M2JXTzNTQzJwZXd1T21uazhYb2hJCjFvc0JKd2ZtS3NNOFl6TzJvUUQz
        L1hMVzIyNVpVR3l3STVMK3o1aHRtbk0KLS0tIGNwRTF2OFU1VFlVLzhiNnlJUCtL
        WWFubmozVUtJRkFJaUx6Z0M4QTlZZEUKzI23tRFS5I8yGYYOlhyOIqBaZB1+BI7o
        LnwvHmwkplIZFCKQgLhgSoL8er1IEGogLlHvrNjq1rTPGX2yKeVDIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T14:04:13Z"
  mac: ENC[AES256_GCM,data:f+HnzP3muDSv/SjoNOzxCpBdNAa7EjOu6LQPArV7rooye60nbsu6q0KPx9mJhGzN9I7oV2NvbwkoPsLKPBw/seKk7N3ZcZiDiv9LDT9O5UKF7UxFrEnx9fHyYssB3k/5xeWtLdrPfUPXiJiRKvaG6O8MbmyOv04S7PVTN/su6tk=,iv:fDO1CQ3lPSHw3fF+tA/RYnbwkqVOJRUW1eNZO21Uq9c=,tag:SwO4yrJZk0BxDht2tQbfJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
