apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omniverse-pvc
  namespace: omniverse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 30Gi
