apiVersion: v1
kind: Secret
metadata:
    name: git-secret
    namespace: omniverse
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:EJn+opCYu1DDPqFS,iv:kiwsApcGrFO1lX+f4UGGfkgEuYVuZ4DVYWEKo3w8WT0=,tag:OtHIRO9QxZjHeR4ErVvyXQ==,type:str]
    token: ENC[AES256_GCM,data:C3snX15Yjfcen2PI/07t4RYy2ErZ18oEwFxabBu2VtegMqFg7KMJfur1s4GG4asLZ+aIvP13qXRpAFelgLS3YhkBxb2mz8HoUhbVnBfZZ+eN43196mdM4ft93Bj4,iv:+zEdnyR8aFw18/ppqTW1xQQ+6iJ6PMGW6J04e3qEMLs=,tag:PoJYiZynP4tsBIO5iyY7SA==,type:str]
sops:
    age:
        - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdHFHK3IzV1p4cEt2RDhy
            OXF4QnFpdW13UE82UjNNNG9ScEdHM0s5WG5jCmY3YnNNUXorSFd5Z3hvV3RRdGls
            Qjd1S254YXg3OE9HcC9mc21BZ2tOS0kKLS0tIEVhUFNsRFA1VWNUTnhmamk4cm5r
            eGc0R0FlTVZuaDlPQ29qb3hsd2Q5LzAKP0Ba3/pCJic3gHZ12JfsWm4C1weCP7l4
            Tt1kSD7th36qEnrYIKr5H/g7XjPBAmF0qCCQK+KGRfQHMHvzt+fLXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-31T19:08:41Z"
    mac: ENC[AES256_GCM,data:Pb2QJJajno35rs+UPokN69DjhjfA2Tqo2hc+hhcDplsoVu93O7O89bEpi0e/M4sn4vd8IDhXHgDyVWURHY3ClOYDCYLu07Bt/Cy+Zqq9ZRc9psg++XDXvKICeQSl/HNRuGm8coa5c+rhDab/2SmQ87ifdqoiBSC2oXU/So5eXmA=,iv:zeISlaoB96kAxvKlQZ5WplgvovxI0xjoOCn+uf2bRgU=,tag:4xrmriQewAlLuF9lGB+yrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
