apiVersion: v1
kind: Secret
metadata:
    name: git-secret
    namespace: omniverse
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Rn7muoRMbapXyOqO,iv:8YKz5Vi7gJrXozeqVH0oPZA9vzcIaJFH/au4KLmU068=,tag:Hl9Y4CrbxLHyu+fqE8lCWQ==,type:str]
    token: ENC[AES256_GCM,data:emj5YAGqzc6Abi3cV0GjkFIBBqahmKWrA1IaDv75emQ93/hrIVb/WfQMWl2Fe5JVMxMSDpoK9dkUhR3Qvk1ho6Ofn3O0aEA1SvwOduuvi98Q2hegChZzch59dtuf,iv:qcJLwj48KZrkZyfnT1lZDnIjnR7CRpg8DN5OcrbqoeE=,tag:nJjRFvOv0G7H35VmqMxJVg==,type:str]
sops:
    age:
        - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHIxUWpQRnZCUGt5Q2ta
            RTRvZTlpdWVMNmdhWnZRYXdacWhRbVQ3MnpZCm1nVndzSUtZbW45TCtKWERxalRt
            WHcyeE9NVDd0MVdXWEJuVW9IUml1bU0KLS0tIGpPOEV2S0E5amZ0cVRTd1JVTUhs
            RXdjUnA5Z3RxUExMVzdLRnQ1QTM3T2cKNwcooDU4oZsK3KKsE07Id/zkgqnXfRRs
            X98Am+F7r6amGmBZ22qjB3h6fuIXqSlj6BHpJHf6TDOMuCBlPe6cXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-31T20:08:18Z"
    mac: ENC[AES256_GCM,data:4IEc8gR8Q7XtkLUFgTbvgYowhRWoLDd3AjK/NWutAAAGUReOMlyGUkCrlJml63iTHeYMEDi6WScF3T6e1vsmB2g0vmU4fcUtfM2Z3NQDB9QFCf2boIvndw4vhDkif+fZDkctpcDtf2ToJsuDMu58w5BwpCYV2oMj9IatmXCo8Nc=,iv:bmzA+MyWMQOH7/2SUlz/bJtci+SHCf+U7t1+Lhtz4OU=,tag:xl22+4VsF0S465jsu3lyQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: webdav-secret
    namespace: omniverse
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:OBhv54Hi0ATV,iv:xaeyQYTacQb3GE3ze4q4WJh0wlb25+ivO55jgr9y8zs=,tag:1rxlKOyvG7a12yLduMHdHg==,type:str]
    password: ENC[AES256_GCM,data:5wQqTiV/bzOdNpLGH++c+NUXG48=,iv:h92UDBJgMB6up7SjT6nuJfqbJ4ncmg1Oz4uDsGLVJpU=,tag:X6MJILyoTt5relGqHoBHAw==,type:str]
sops:
    age:
        - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHIxUWpQRnZCUGt5Q2ta
            RTRvZTlpdWVMNmdhWnZRYXdacWhRbVQ3MnpZCm1nVndzSUtZbW45TCtKWERxalRt
            WHcyeE9NVDd0MVdXWEJuVW9IUml1bU0KLS0tIGpPOEV2S0E5amZ0cVRTd1JVTUhs
            RXdjUnA5Z3RxUExMVzdLRnQ1QTM3T2cKNwcooDU4oZsK3KKsE07Id/zkgqnXfRRs
            X98Am+F7r6amGmBZ22qjB3h6fuIXqSlj6BHpJHf6TDOMuCBlPe6cXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-31T20:08:18Z"
    mac: ENC[AES256_GCM,data:4IEc8gR8Q7XtkLUFgTbvgYowhRWoLDd3AjK/NWutAAAGUReOMlyGUkCrlJml63iTHeYMEDi6WScF3T6e1vsmB2g0vmU4fcUtfM2Z3NQDB9QFCf2boIvndw4vhDkif+fZDkctpcDtf2ToJsuDMu58w5BwpCYV2oMj9IatmXCo8Nc=,iv:bmzA+MyWMQOH7/2SUlz/bJtci+SHCf+U7t1+Lhtz4OU=,tag:xl22+4VsF0S465jsu3lyQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
