apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: omniverse
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "omniverse-webdav"
spec:
  selector:
    app: webdav
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
