apiVersion: v1
kind: Secret
metadata:
  name: audiomuse-ai-secrets
  namespace: default
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:LaYi4KQv4Sz0BDsONs9D2Vl5qT3ZvCIW7pbv8wWoaNt+FkUrbVbxzYUMJgiLwDEx1pMyqdFPl4vMya4zDRY=,iv:yvNYl+aXtJTiH9k2NxfFr55ia/Sg12yL/5R+zavoqm4=,tag:150vQmzzPo3UxpQ7NGUJxA==,type:str]
sops:
  age:
    - recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ3FodVMyWXF2S0xwcEFa
        Sk1Cdnh0QytkWUNYaXdnMDNyWjA3Z3BGTEdvClZKTSsvTUtyTVlJRm1WbUk0STlh
        YUVPbFJPcTJ4Z1BuRjlwdHhPOGJ5MlEKLS0tIHFWMDdmVzJsSjd3Q1BTYlRVbWxT
        ai9TU3pVMkJ5VnVmMEdEVWRSVHpMOHMK4HYqncdu0L1fdOV5KyN1FENimcVnROyw
        6sw/gvlfE7VAFmZVAs7RNvW7vazetoyAqGsDHNGg0Uf41jhBZcSb/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T21:43:00Z"
  mac: ENC[AES256_GCM,data:mTmPoPGrB30Ak6aT/P8w+GoYB5H2V+BjeFq29jl8VNxiTpvDx5mjPbz9Bl+kF66N4tNtvQkUouH/N/XVEsM+5M/fVOcRN8Xqb4nvG+dPhRfWNeqpavI5eLTiUf5D967Vg2PZXQsqyiEQdeNH0+Nc7gqdfV+Df0N7kbdR6jupCrc=,iv:3ulfPccOeFP7XmmKHa2bt1xtwo1RwEhpiFnQbunY9UQ=,tag:CHn5H5x1zJJHVSj4e7AljQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
